
server:
  port: 1111
  
management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bhaskaradb?createDatabaseIfNotExist=true
    username: root
    password: boss
  jpa:
    database: mysql
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    
    