
server:
  port: 1111
  
management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  datasource:
    driver-class-name: 
    url: 
    username: 
    password: 
  jpa:
    database: mysql
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    
    